spring.application.name=c451-final-project-team-crocodile
server.port=8080
spring.datasource.url=jdbc:h2:mem:tripwire
dymo.api.verify-url=https://api.tpeoficial.com/v1/private/secure/verify
dymo.api.token=${DYMO_API_TOKEN:}
